public with sharing class Constants {
    public static final String SUCCESS = 'Success';
    public static final String TYPE_INITIAL_PAYMENT = 'Initial Payment';
    public static final String TYPE_SECURITY_DEPOSIT = 'Security Deposit';
    public static final String TYPE_PARTIAL_PAYMENT = 'Partial Payment';
    public static final String BOOKING_PAID = 'Paid';
    public static final String BOOKING_PARTIAL_PAID = 'Partially Paid';
    public static final String BOOKING_PAYMENT_PENDING = 'Pending';
    public static final String BOOKING_PENDING_STATUS = 'Pending';
    public static final String BOOKING_CONFIRM_STATUS = 'Confirmed';
    public static final String BOOKING_STARTED_STATUS = 'Started';
    public static final String BOOKING_COMPLETED_STATUS = 'Completed';
    public static final String BOOKING_CLOSED_STATUS = 'Closed';
    public static final Integer LOW_RATING_THRESHOLD = 3;
    public static final Integer DEFAULT_RATING_THRESHOLD = 5;
    public static final String CUSTOMER_SUPPORT_PUBLIC_GROUP = 'Customer_Support';
    public static final String NEGATIVE_REVIEW_RECORD_TYPE = 'Review_Issue';
    public static final String NEGATIVE_REVIEW_CASE_TYPE = 'Negative Review';
    public static final String CASE_PRIORITY_MEDIUM = 'Medium';
    public static final String SECURITY_DEPOSIT_THRESHOLD = 'Security_Deposit_Percentage';
    public static final String AVAILABLE_CARS = 'Available';
    public static final String STATUS_EMAIL = 'deliverable';
    public static final String STATUS_DETAIL_EMAIL = 'valid_email';
    
}